name: scrapingdata

on:
  schedule:
    - cron: '*/5 * * * * '

jobs:
  scraping:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'

      # - name: Cache pip
      #   uses: actions/cache@v1
      #   with:
      #     path: ~/.cache/pip 
      #     key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
      #     restore-keys: |
      #       ${{ runner.os }}-pip-
      #       ${{ runner.os }}-

      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt

      # - name: Run scraping
      #   run: python ./tool/scraping.py
